# Generated by Django 4.2.9 on 2026-01-16 18:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(help_text='Admin Telegram user ID', max_length=100, unique=True)),
                ('full_name', models.CharField(help_text='Admin ismi', max_length=255)),
                ('username', models.CharField(blank=True, help_text='Telegram @username', max_length=100)),
                ('is_superadmin', models.BooleanField(default=False, help_text='Super admin (barcha huquqlar)')),
                ('is_active', models.BooleanField(default=True, help_text='Admin faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Adminlar',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(help_text='Sotuvchi telefon raqami (+998901234567)', max_length=20, unique=True)),
                ('full_name', models.CharField(help_text="Sotuvchining to'liq ismi", max_length=255)),
                ('telegram_user_id', models.CharField(blank=True, help_text='Sotuvchining Telegram user ID', max_length=100)),
                ('telegram_username', models.CharField(blank=True, help_text='Sotuvchining @username', max_length=100)),
                ('group_chat_id', models.CharField(help_text='Buyurtmalar yuboriladigan Telegram guruh ID', max_length=100, unique=True)),
                ('group_invite_link', models.CharField(blank=True, help_text='Guruhga taklif havolasi', max_length=500)),
                ('group_title', models.CharField(blank=True, help_text='Guruh nomi', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Sotuvchi faolmi?')),
                ('api_identifier', models.CharField(blank=True, help_text="Tashqi API'dagi sotuvchi identifikatori", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sotuvchi',
                'verbose_name_plural': 'Sotuvchilar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone'], name='bot_seller_phone_4dccc7_idx'), models.Index(fields=['telegram_user_id'], name='bot_seller_telegra_a2923d_idx'), models.Index(fields=['is_active'], name='bot_seller_is_acti_be577b_idx'), models.Index(fields=['api_identifier'], name='bot_seller_api_ide_20e2ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(help_text="Tashqi API'dagi buyurtma ID", max_length=100, unique=True)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi'), ('processing', 'Jarayonda'), ('shipped', 'Yetkazilmoqda'), ('delivered', 'Yetkazildi'), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi')], default='new', max_length=50)),
                ('customer_name', models.CharField(help_text='Mijoz ismi', max_length=255)),
                ('customer_phone', models.CharField(help_text='Mijoz telefon raqami', max_length=20)),
                ('customer_address', models.TextField(blank=True, help_text='Yetkazib berish manzili')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Buyurtma umumiy summasi', max_digits=12)),
                ('items', models.JSONField(default=list, help_text="Mahsulotlar ro'yxati (JSON)")),
                ('notes', models.TextField(blank=True, help_text="Qo'shimcha izohlar")),
                ('accepted_by', models.CharField(blank=True, help_text='Qabul qilgan operator', max_length=255)),
                ('accepted_at', models.DateTimeField(blank=True, help_text='Qabul qilingan vaqt', null=True)),
                ('telegram_message_id', models.CharField(blank=True, help_text='Yuborilgan Telegram xabar ID', max_length=100)),
                ('telegram_chat_id', models.CharField(blank=True, help_text='Xabar yuborilgan chat ID', max_length=100)),
                ('notified_at', models.DateTimeField(blank=True, help_text='Notification yuborilgan vaqt', null=True)),
                ('created_at', models.DateTimeField(help_text="Buyurtma yaratilgan vaqt (API'dan)")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(blank=True, help_text='Buyurtma biriktirilgan sotuvchi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='bot.seller')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['external_id'], name='bot_order_externa_9aa152_idx'), models.Index(fields=['status'], name='bot_order_status_3faa9a_idx'), models.Index(fields=['seller', 'status'], name='bot_order_seller__1a4daa_idx'), models.Index(fields=['created_at'], name='bot_order_created_7d6ad4_idx'), models.Index(fields=['customer_phone'], name='bot_order_custome_ca3f1c_idx')],
            },
        ),
    ]
